# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit_source_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditSource(object):
    def setupUi(self, EditSource):
        EditSource.setObjectName("EditSource")
        EditSource.resize(1161, 680)
        self.centralwidget = QtWidgets.QWidget(EditSource)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.splitter.setLineWidth(2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(10)
        self.splitter.setObjectName("splitter")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_rebuild = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_rebuild.setFont(font)
        self.btn_rebuild.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(61, 217, 245), stop:1 rgb(240, 53, 218));\n"
"border-style: solid;\n"
"border-radius:21px;\n"
"font-weight: bold;\n"
"color: rgb(255, 255, 255);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/rebuild"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_rebuild.setIcon(icon)
        self.btn_rebuild.setIconSize(QtCore.QSize(20, 20))
        self.btn_rebuild.setObjectName("btn_rebuild")
        self.horizontalLayout_2.addWidget(self.btn_rebuild)
        self.line_2 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_2.addWidget(self.line_2)
        self.btn_save = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_save.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/save"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_save.setIcon(icon1)
        self.btn_save.setIconSize(QtCore.QSize(20, 20))
        self.btn_save.setObjectName("btn_save")
        self.horizontalLayout_2.addWidget(self.btn_save)
        self.btn_reload = QtWidgets.QPushButton(self.verticalLayoutWidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/refresh"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_reload.setIcon(icon2)
        self.btn_reload.setIconSize(QtCore.QSize(20, 20))
        self.btn_reload.setObjectName("btn_reload")
        self.horizontalLayout_2.addWidget(self.btn_reload)
        self.pushButtonHideHelp = QtWidgets.QPushButton(self.verticalLayoutWidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/basic/info_help"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonHideHelp.setIcon(icon3)
        self.pushButtonHideHelp.setIconSize(QtCore.QSize(20, 20))
        self.pushButtonHideHelp.setObjectName("pushButtonHideHelp")
        self.horizontalLayout_2.addWidget(self.pushButtonHideHelp)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.undo = QtWidgets.QPushButton(self.verticalLayoutWidget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/delete"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.undo.setIcon(icon4)
        self.undo.setObjectName("undo")
        self.horizontalLayout.addWidget(self.undo)
        self.zoomin = QtWidgets.QPushButton(self.verticalLayoutWidget)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/plot/zoom"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoomin.setIcon(icon5)
        self.zoomin.setObjectName("zoomin")
        self.horizontalLayout.addWidget(self.zoomin)
        self.zoomout = QtWidgets.QPushButton(self.verticalLayoutWidget)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/plot/zoom_out"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoomout.setIcon(icon6)
        self.zoomout.setObjectName("zoomout")
        self.horizontalLayout.addWidget(self.zoomout)
        self.center = QtWidgets.QPushButton(self.verticalLayoutWidget)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/plot/zoom_target"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.center.setIcon(icon7)
        self.center.setObjectName("center")
        self.horizontalLayout.addWidget(self.center)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.src_editor = MetalSourceEditor(self.verticalLayoutWidget)
        self.src_editor.setObjectName("src_editor")
        self.verticalLayout.addWidget(self.src_editor)
        self.lineSrcPath = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineSrcPath.setReadOnly(True)
        self.lineSrcPath.setObjectName("lineSrcPath")
        self.verticalLayout.addWidget(self.lineSrcPath)
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.textEditHelp = QtWidgets.QTextEdit(self.layoutWidget)
        self.textEditHelp.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.textEditHelp.setReadOnly(True)
        self.textEditHelp.setObjectName("textEditHelp")
        self.verticalLayout_2.addWidget(self.textEditHelp)
        self.verticalLayout_3.addWidget(self.splitter)
        EditSource.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(EditSource)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1161, 22))
        self.menubar.setObjectName("menubar")
        EditSource.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(EditSource)
        self.statusBar.setObjectName("statusBar")
        EditSource.setStatusBar(self.statusBar)

        self.retranslateUi(EditSource)
        self.btn_save.clicked.connect(self.src_editor.save_file)
        self.btn_reload.clicked.connect(self.src_editor.reload_file)
        self.zoomout.clicked.connect(self.src_editor.zoomOut)
        self.zoomin.clicked.connect(self.src_editor.zoomIn)
        self.undo.clicked.connect(self.src_editor.undo)
        self.center.clicked.connect(self.src_editor.centerCursor)
        self.btn_rebuild.clicked.connect(self.src_editor.rebuild_components)
        self.pushButtonHideHelp.clicked.connect(self.src_editor.hide_help)
        QtCore.QMetaObject.connectSlotsByName(EditSource)

    def retranslateUi(self, EditSource):
        _translate = QtCore.QCoreApplication.translate
        EditSource.setWindowTitle(_translate("EditSource", "Edit source code"))
        self.btn_rebuild.setText(_translate("EditSource", "Rebuild Component"))
        self.btn_rebuild.setShortcut(_translate("EditSource", "Ctrl+R, Meta+R"))
        self.btn_save.setText(_translate("EditSource", "Save File"))
        self.btn_save.setShortcut(_translate("EditSource", "Ctrl+S, Meta+S"))
        self.btn_reload.setText(_translate("EditSource", "Reload File"))
        self.pushButtonHideHelp.setText(_translate("EditSource", "Help"))
        self.undo.setText(_translate("EditSource", "Undo"))
        self.zoomin.setText(_translate("EditSource", "Zoom in"))
        self.zoomout.setText(_translate("EditSource", "Zoom out"))
        self.center.setText(_translate("EditSource", "Center"))
        self.src_editor.setPlainText(_translate("EditSource", "Source comes here"))
        self.lineSrcPath.setText(_translate("EditSource", "Source code file path here"))
        self.textEditHelp.setDocumentTitle(_translate("EditSource", "Help"))
        self.textEditHelp.setHtml(_translate("EditSource", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><title>Help</title><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:22.4px; background-color:#ffffff;\"><span style=\" font-family:\'Arial\'; font-size:16px; font-weight:600; color:#797a7a; background-color:#ffffff;\">Help me?</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:22.4px; background-color:#ffffff;\"><span style=\" font-family:\'Arial\'; font-size:16px; font-style:italic; color:#797a7a; background-color:#ffffff;\">Double click </span><span style=\" font-family:\'Arial\'; font-size:16px; color:#797a7a; background-color:#ffffff;\">any function or class in the source code to view its documentation. </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:22.4px; background-color:#ffffff;\"><span style=\" font-family:\'Arial\'; font-size:16px; color:#797a7a; background-color:#ffffff;\">Documentation is also shown anytime one types</span><span style=\" font-family:\'Arial\'; font-size:16px; color:#797a7a;\"> a bracket </span><span style=\" font-family:\'Arial\'; font-size:16px; color:#797a7a;\">(</span><span style=\" font-family:\'Arial\'; font-size:16px; color:#797a7a;\"> after the name of a function. </span><span style=\" font-family:\'Arial\'; font-size:16px; color:#797a7a; background-color:#ffffff;\">For example, enter</span><span style=\" font-family:\'Arial\'; font-size:16px; color:#797a7a;\"> </span><span style=\" font-family:\'Arial\'; font-size:16px; color:#797a7a; background-color:#ecf0f3;\">draw.rectangle(</span><span style=\" font-family:\'Arial\'; font-size:16px; color:#797a7a;\">, and a  calltip will appear here.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:22.4px; font-family:\'Arial\'; font-size:16px; color:#797a7a; background-color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:22.4px; background-color:#ffffff;\"><span style=\" font-family:\'Arial\'; font-size:16px; font-weight:600; color:#797a7a;\">Hide help panel? </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:22.4px; background-color:#ffffff;\"><span style=\" font-family:\'Arial\'; font-size:16px; color:#797a7a;\">Drag the slider in the middle all the way to the right. </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:22.4px; font-family:\'Arial\'; font-size:16px; color:#797a7a; background-color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:22.4px; background-color:#ffffff;\"><span style=\" font-family:\'Arial\'; font-size:16px; font-weight:600; color:#797a7a;\">Search, replace, and more?</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:22.4px; background-color:#ffffff;\"><span style=\" font-family:\'Arial\'; font-size:16px; color:#797a7a;\">Right click the source code to view more.</span></p></body></html>"))
from .widgets.edit_component.source_editor import MetalSourceEditor
from . import main_window_rc_rc
