#!/bin/bash

echo "Checking dependencies"
which yapf &> /dev/null
ret=$?
if [[ $ret != 0 ]]; then
    echo "Please install yapf to use pre-commit hook"
    exit 1
else
    echo "All dependencies present"
fi

echo "Begin linting step using yapf formatting"
linterrorfound=0
for stagedfile in $(git diff --name-only --cached | grep ".*\.py")
do
    yapf --diff --style .style.yapf $stagedfile
    ret=$?
    if [[ $ret != 0 ]]; then
        linterrorfound=1
        echo ">>> Errors in file $stagedfile"
    fi
done

if [[ $linterrorfound == 1 ]]; then
    echo "Please fix linting errors before committing"
    exit 1
else
    echo "Linting successful"
fi

echo "Python linting validation completed!"
exit 0
