# This code is part of Qiskit.
#
# (C) Copyright IBM 2017, 2023.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

# pylint: disable=invalid-name
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys

sys.path.insert(0, os.path.abspath('..'))

import qiskit_metal
import qiskit_sphinx_theme
"""
Sphinx documentation builder
"""

# The short X.Y version
version = qiskit_metal.__version__
# The full version, including alpha/beta/rc tags
release = qiskit_metal.__version__

rst_prolog = """
.. raw:: html

    <br><br><br>

.. |version| replace:: {0}
""".format(release)

# -- Project information -----------------------------------------------------
project = 'Qiskit Metal {}'.format(version)
copyright = '2019, Qiskit Development Team'  # pylint: disable=redefined-builtin
author = 'Qiskit Metal Development Team'
# -- General configuration ---------------------------------------------------

extensions = [
    'sphinx.ext.napoleon', 'sphinx.ext.autodoc', 'sphinx.ext.autosummary',
    'sphinx.ext.mathjax', 'sphinx.ext.viewcode', 'sphinx.ext.extlinks',
    'jupyter_sphinx', 'nbsphinx',
    "qiskit_sphinx_theme",
]

html_static_path = ['_static']
templates_path = ['_templates']

exclude_patterns = [
    '_build', 'build', '*.ipynb', '**.ipynb_checkpoints', '_utility'
]


nbsphinx_execute = os.getenv('QISKIT_DOCS_BUILD_TUTORIALS', 'never')

source_suffix = ['.rst', '.ipynb']

suppress_warnings = ['ref.ref']

nbsphinx_thumbnails = {
    'tut/quick-topics/Opening-documentation':
        '_static/qt-open-docs.png',
    'tut/4-Analysis/4.31-Plot-quantum-oscillator-wavefunction':
        '_static/4-31-plotting-wavefunction.png',
    'tut/4-Analysis/4.32-Transmon-analytics-HCPB':
        '_static/4-32-transmon-hcpb.png',
    'tut/4-Analysis/4.33-Transmon-analytics':
        '_static/4-33-transmon-analytics.png',
    'tut/4-Analysis/4.34-Transmon-qubit-CPB-hamiltonian-charge-basis':
        '_static/4-34-transmon-cpb.png',
    'tut/4-Analysis/4.15-CPW-kappa-calculation':
        '_static/4-15-kappa-calc.png',
    'tut/1-Overview/1.3-Saving-Your-Chip-Design':
        '_static/1-3-save.png',
}

# -----------------------------------------------------------------------------
# Autosummary
# -----------------------------------------------------------------------------
autosummary_generate = True

# -----------------------------------------------------------------------------
# Autodoc
# -----------------------------------------------------------------------------

autodoc_default_options = {
    'inherited-members': None,
}

autoclass_content = 'both'

# If true, figures, tables and code-blocks are automatically numbered if they
# have a caption.
numfig = True

# A dictionary mapping 'figure', 'table', 'code-block' and 'section' to
# strings that are used for format of figure numbers. As a special character,
# %s will be replaced to figure number.
numfig_format = {'table': 'Table %s'}
# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# A boolean that decides whether module names are prepended to all object names
# (for object types where a “module” of some kind is defined), e.g. for
# py:function directives.
add_module_names = False

# A list of prefixes that are ignored for sorting the Python module index
# (e.g., if this is set to ['foo.'], then foo.bar is shown under B, not F).
# This can be handy if you document a project that consists of a single
# package. Works only for the HTML builder currently.
modindex_common_prefix = ['qiskit_metal.']

# -- Configuration for extlinks extension ------------------------------------
# Refer to https://www.sphinx-doc.org/en/master/usage/extensions/extlinks.html

# -- Options for HTML output -------------------------------------------------

html_theme = "qiskit_sphinx_theme"

html_logo = 'images/logo.png'
html_last_updated_fmt = '%Y/%m/%d'

html_theme_options = {
    'logo_only': False,
    'display_version': True,
    'prev_next_buttons_location': 'bottom',
    'style_external_links': True,
    'collapse_navigation': True,
    'sticky_navigation': True,
}
